// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRolW-mvg48MmK_rp_w-KewJeh7bCWAk',
    appId: '1:88786807723:web:dc783d66cf2aac737180ee',
    messagingSenderId: '88786807723',
    projectId: 'chat-app-f34a7',
    authDomain: 'chat-app-f34a7.firebaseapp.com',
    storageBucket: 'chat-app-f34a7.firebasestorage.app',
    measurementId: 'G-3PH9QL63D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0sAyxA5hO86zQXsCvYO035zuvQ3XBjM',
    appId: '1:88786807723:android:793040f031fb1ca57180ee',
    messagingSenderId: '88786807723',
    projectId: 'chat-app-f34a7',
    storageBucket: 'chat-app-f34a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzjHLXdjG3fTUSWwm49UBG5VDx3-nUzdw',
    appId: '1:88786807723:ios:23f8de92a226b4c57180ee',
    messagingSenderId: '88786807723',
    projectId: 'chat-app-f34a7',
    storageBucket: 'chat-app-f34a7.firebasestorage.app',
    iosBundleId: 'com.example.chatScolerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzjHLXdjG3fTUSWwm49UBG5VDx3-nUzdw',
    appId: '1:88786807723:ios:23f8de92a226b4c57180ee',
    messagingSenderId: '88786807723',
    projectId: 'chat-app-f34a7',
    storageBucket: 'chat-app-f34a7.firebasestorage.app',
    iosBundleId: 'com.example.chatScolerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRolW-mvg48MmK_rp_w-KewJeh7bCWAk',
    appId: '1:88786807723:web:fe31842803c56b9d7180ee',
    messagingSenderId: '88786807723',
    projectId: 'chat-app-f34a7',
    authDomain: 'chat-app-f34a7.firebaseapp.com',
    storageBucket: 'chat-app-f34a7.firebasestorage.app',
    measurementId: 'G-LTDTT59XDN',
  );
}
